language: rust
sudo: false

rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev

before_script:
- |
    pip install 'travis-cargo<0.2' --user &&
    export PATH=$HOME/.local/bin:$PATH


script:
  - |
    (
    cd quasi &&
    travis-cargo build -- --features with-syntex &&
    travis-cargo test -- --features with-syntex &&
    travis-cargo --only nightly build &&
    travis-cargo --only nightly test &&
    travis-cargo doc --features with-syntex
    )
  - |
    (
    cd quasi_macros &&
    travis-cargo --only nightly build &&
    travis-cargo --only nightly test
    )
  - |
    (
    cd quasi_tests &&
    travis-cargo build &&
    travis-cargo test
    )

after_success:
  - |
    (
    cd quasi &&
    travis-cargo --only stable doc-upload
    )
  - |
    (
    cd quasi_tests &&
    travis-cargo --only stable coveralls --no-sudo
    )

env:
  global:
    # override the default `--features unstable` used for the nightly branch (optional)
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""

    # encrypted github token for doc upload (see `GH_TOKEN` link above)
    - secure: VdytY7YA8W4q146sMv7vc7G8UBSmEtQC4NImNicffnXXVu/ghbKu+/6knmjDc97mjiz7AdredJzE/lUI3Np9PqONvtMFv8Mzcbcm0vglybIFxEGgNz82dr9wzZ6UnWZu1vULGVnKi1N2sXwYsourEex6Ec4rp89vXshQxYV58tI=
