[package]
name = "quasi_tests"
version = "0.5.1"
authors = ["Erick Tryzelaar <erick.tryzelaar@gmail.com>"]
license = "MIT/Apache-2.0"
description = "A quasi-quoting macro system"
repository = "https://github.com/erickt/rust-quasi"
build = "build.rs"

[build-dependencies]
quasi_codegen = { path = "../quasi_codegen" }
syntex = { version = "^0.30.0" }

[dev-dependencies]
aster = { version = "^0.14.0", features = ["with-syntex"] }
quasi = { path = "../quasi", features = ["with-syntex"] }
syntex = { version = "^0.30.0" }
syntex_syntax = { version = "^0.30.0" }
