[package]
name = "quasi"
version = "0.3.1"
authors = ["Erick Tryzelaar <erick.tryzelaar@gmail.com>"]
license = "MIT/Apache-2.0"
description = "A quasi-quoting macro system"
repository = "https://github.com/erickt/rust-quasi"

[features]
with-syntex = ["syntex_syntax"]

[dependencies]
syntex_syntax = { version = "*", optional = true }
